pp-test:
  build: .
  ports:
    - "8089:80"
#    - "4443:443"
  volumes:
    - ../:/code
    - ../logs/nginx:/var/log/nginx
    - ./config/nginx.conf:/etc/nginx/sites-enabled/default
#    - /etc/timezone:/etc/timezone:ro
#    - /etc/localtime:/etc/localtime:ro
